version: "3.8"

services:
  server:
    image: nestjs-server
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:3000
    
    volumes:
      - ./:/app
      - ./package.json:/app/package.json
      - /app/node_modules